

CREATE SEQUENCE CLIENTES_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE PRODUCTOS_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE PEDIDOS_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE PEDIDOS_PRODUCTOS|_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


CREATE TABLE CLIENTES(
ID_CLIENTE NUMBER DEFAULT CLIENTES_SEQ.NEXTVAL,
NOMBRE VARCHAR2(50)NOT NULL,
APELLIDO VARCHAR2(50)NOT NULL,
EMAIL VARCHAR(100)NOT NULL UNIQUE,
TELEFONO NUMBER NOT NULL UNIQUE,
DIRECCION VARCHAR(100),
PRIMARY KEY (ID_CLIENTE)
);

--------------------------------------------------------------------------------
CREATE TABLE PRODUCTOS(
ID_PRODUCTO NUMBER DEFAULT PRODUCTOS_SEQ.NEXTVAL,
NOMBRE VARCHAR2(50)NOT NULL,
DESCRIPCION VARCHAR2(100)NOT NULL,
PRECIO NUMBER(10,2) NOT NULL CHECK(PRECIO >= 0),
STOCK NUMBER NOT NULL CHECK (STOCK >= 0),
PRIMARY KEY (ID_PRODUCTO)
);

--------------------------------------------------------------------------------
CREATE TABLE PEDIDOS(
ID_PEDIDO NUMBER DEFAULT PEDIDOS_SEQ.NEXTVAL,
TOTAL NUMBER,
FECHA_CREACION DATE,
ESTADO VARCHAR2(20) NOT NULL CHECK (ESTADO IN ('PENDIENTE','ENVIADO','ENTREGADO','CANCELADO')),
ID_CLIENTE NUMBER,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
PRIMARY KEY (ID_CLIENTE)
);

--------------------------------------------------------------------------------
CREATE TABLE PEDIDOS_PRODUCTOS(
ID_PRODUCTO NUMBER NOT NULL,
ID_PEDIDO NUMBER NOT NULL, 
PRIMARY KEY (ID_PRODUCTO, ID_PEDIDO),
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO)
);

