
server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client-micro
          uri: http://localhost:9090
          predicates:
            - Path=/clientes/**
        - id: product-micro
          uri: http://localhost:9091
          predicates:
            - Path=/productos/**
        - id: order-micro
          uri: http://localhost:9092
          predicates:
            - Path=/ordenes/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: info,health,env
        exclude: beans
  endpoint:
    info:
      enabled: true
    health:
      show-details: always